# -*- coding: utf-8 -*-
"""Copy of Assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Albk8hpFI-PW82IcRnznSjCDRt3uCe8y

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

y=s.split() 
print(y)

"""## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

plant="Earth" 
diameter=12342

print('The diameter of {} is {} Kilometers.' .format(plant,diameter))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

l=[1,2,[3,4],[5,[100,200,['hello']],22,11],1,7] 
asa=l[3][1][2] 
print(asa)

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

import numpy as np 
a=np.zeros(10) 
print("An array of 10 zero:s")
print(a)

a=np.ones(10)*5 
print("An array of 10 fives:")
print(a)

"""## 5. Create an array of all the even integers from 20 to 35"""

a=20 
b=35 
l=[]
for i in range(a,b):
  l.append(i) 
print(l)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as n 
x=n.arange(0,9).reshape(3,3) 
print(x)

"""## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

import numpy as np 
a=np.array([[1,2,3]]) 
b=np.array([[4,5,6]]) 
np.concatenate((a,b),axis=None) 
([1,2,3,4,5,6])

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

d=[['tony',72],['nike',73],['riya',74]] 
f=pd.DataFrame(d,columns=['Name','Age']) 
f

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

import pandas as pd 
p=pd.date_range(start='01-01-2023',end='02-10-2023') 
for f in p:
  print(f)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

import pandas as p 
l=[['aaa',22],['bbb',25],['ccc',24]] 
d=pd.DataFrame(l,)
print(d)